//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmanUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChildrenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChildrenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmanUI.Resources.ChildrenResources", typeof(ChildrenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Activities.
        /// </summary>
        public static string ActivitiesPageName {
            get {
                return ResourceManager.GetString("ActivitiesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities sum.
        /// </summary>
        public static string ActivitiesSum {
            get {
                return ResourceManager.GetString("ActivitiesSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Child Bill.
        /// </summary>
        public static string CalculateChildBill {
            get {
                return ResourceManager.GetString("CalculateChildBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alman Calendar for dates.
        /// </summary>
        public static string CalendarWindow {
            get {
                return ResourceManager.GetString("CalendarWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Activity.
        /// </summary>
        public static string ChildActivityName {
            get {
                return ResourceManager.GetString("ChildActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alman Child Bill.
        /// </summary>
        public static string ChildBillWindow {
            get {
                return ResourceManager.GetString("ChildBillWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Name.
        /// </summary>
        public static string ChildFirstName {
            get {
                return ResourceManager.GetString("ChildFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ChildGroup {
            get {
                return ResourceManager.GetString("ChildGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Last Name.
        /// </summary>
        public static string ChildLastName {
            get {
                return ResourceManager.GetString("ChildLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string ChildrenPageName {
            get {
                return ResourceManager.GetString("ChildrenPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Contract Fees.
        /// </summary>
        public static string ContractFeesPageName {
            get {
                return ResourceManager.GetString("ContractFeesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Fees Sum.
        /// </summary>
        public static string ContractFeesSum {
            get {
                return ResourceManager.GetString("ContractFeesSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Contract.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill dates of presence.
        /// </summary>
        public static string FillDatesToolTip {
            get {
                return ResourceManager.GetString("FillDatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Capital.
        /// </summary>
        public static string MotherCapitalType {
            get {
                return ResourceManager.GetString("MotherCapitalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary.
        /// </summary>
        public static string OrdinaryContractType {
            get {
                return ResourceManager.GetString("OrdinaryContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string OverallSum {
            get {
                return ResourceManager.GetString("OverallSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Precontracts.
        /// </summary>
        public static string PrecontractsPageName {
            get {
                return ResourceManager.GetString("PrecontractsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precontracts sum.
        /// </summary>
        public static string PrecontractsSum {
            get {
                return ResourceManager.GetString("PrecontractsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precontract.
        /// </summary>
        public static string PrecontractType {
            get {
                return ResourceManager.GetString("PrecontractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for one time.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Child.
        /// </summary>
        public static string StaffChildType {
            get {
                return ResourceManager.GetString("StaffChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Children Activities.
        /// </summary>
        public static string YearMonthActivitiesPageName {
            get {
                return ResourceManager.GetString("YearMonthActivitiesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Year Subscriptions.
        /// </summary>
        public static string YearSubsPageName {
            get {
                return ResourceManager.GetString("YearSubsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Subscriptions sum.
        /// </summary>
        public static string YearSubsSum {
            get {
                return ResourceManager.GetString("YearSubsSum", resourceCulture);
            }
        }
    }
}
