//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmanUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OtherResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmanUI.Resources.OtherResources", typeof(OtherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExpenseName {
            get {
                return ResourceManager.GetString("ExpenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpensesPageName {
            get {
                return ResourceManager.GetString("ExpensesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth Week.
        /// </summary>
        public static string FifthWeek {
            get {
                return ResourceManager.GetString("FifthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Week.
        /// </summary>
        public static string FirstWeek {
            get {
                return ResourceManager.GetString("FirstWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Week.
        /// </summary>
        public static string FourthWeek {
            get {
                return ResourceManager.GetString("FourthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Activity.
        /// </summary>
        public static string OtherActivityName {
            get {
                return ResourceManager.GetString("OtherActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Sum.
        /// </summary>
        public static string OverallSum {
            get {
                return ResourceManager.GetString("OverallSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Week.
        /// </summary>
        public static string SecondWeek {
            get {
                return ResourceManager.GetString("SecondWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Week.
        /// </summary>
        public static string ThirdWeek {
            get {
                return ResourceManager.GetString("ThirdWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Other Activities.
        /// </summary>
        public static string YearMonthOtherPageName {
            get {
                return ResourceManager.GetString("YearMonthOtherPageName", resourceCulture);
            }
        }
    }
}
