//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmanUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaffResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaffResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlmanUI.Resources.StaffResources", typeof(StaffResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Payment.
        /// </summary>
        public static string FinalPayment {
            get {
                return ResourceManager.GetString("FinalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Payment was paid.
        /// </summary>
        public static string FinalPaymentWasPaid {
            get {
                return ResourceManager.GetString("FinalPaymentWasPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string PositionSalary {
            get {
                return ResourceManager.GetString("PositionSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment.
        /// </summary>
        public static string Prepayment {
            get {
                return ResourceManager.GetString("Prepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment was paid.
        /// </summary>
        public static string PrepaymentWasPaid {
            get {
                return ResourceManager.GetString("PrepaymentWasPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Monthly Activities .
        /// </summary>
        public static string StaffActivitiesPageName {
            get {
                return ResourceManager.GetString("StaffActivitiesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Activity.
        /// </summary>
        public static string StaffActivityName {
            get {
                return ResourceManager.GetString("StaffActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member Name.
        /// </summary>
        public static string StaffFirstName {
            get {
                return ResourceManager.GetString("StaffFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member Lastname.
        /// </summary>
        public static string StaffLastName {
            get {
                return ResourceManager.GetString("StaffLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Members.
        /// </summary>
        public static string StaffPageName {
            get {
                return ResourceManager.GetString("StaffPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Monthly Payments.
        /// </summary>
        public static string StaffPaymentsPageName {
            get {
                return ResourceManager.GetString("StaffPaymentsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was Paid.
        /// </summary>
        public static string WasPaid {
            get {
                return ResourceManager.GetString("WasPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Staff Activities.
        /// </summary>
        public static string YearMonthStaffActivitiesPageName {
            get {
                return ResourceManager.GetString("YearMonthStaffActivitiesPageName", resourceCulture);
            }
        }
    }
}
