# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        #cache: true
        #cache-dependency-path: /home/runner/work/alman/alman/packages.lock.json
    # - name: Restore dependencies
    #   run: dotnet restore
    - name: Install dependencies
      run: |
        cd /home/runner/work/alman/alman/src/db_access
        dotnet add package Microsoft.Data.Sqlite.Core --version 8.0.7
        dotnet add package Microsoft.EntityFrameworkCore --version 8.0.7
        dotnet add package Microsoft.EntityFrameworkCore.Design --version 8.0.7
        dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 8.0.7
        dotnet add package Microsoft.EntityFrameworkCore.Tools --version 8.0.7


    # build of the db as access level
    - name: Build
      run: dotnet build src/db_access/DbAccess.csproj
    # no testing for now as the tests are in non master branch
    - name: Test
      run: |
        cd /home/runner/work/alman/alman/test/DbAccessUnitTests
        dotnet test --verbosity normal
